### ISSUE TITLE
All three games instacrash when attempting to start.

### ISSUE THREAD

**Issue by Shockwave508** [daniele-rapagnani/alephone-android#24]
On my Android 10 phone, with a Razer Kishi controller hooked up to it, all three games only display a black screen for a split-second before instacrashing back to my apps launcher.

**Comment by daniele-rapagnani** [comment]
That's odd! If you know how to use `adb` it would be great if you manage to post the exact error here. You should find it by running `adb logcat` shortly before launching the app and watching for a stack trace on the output.

**Comment by TheUpgrayedd** [comment]
Just tried to play with a controller I got to day and had this issue.
As soon as it starts it instantly closes with the message "AlephOne keeps stopping"
Unplugged the controller and it plays fine.
Started the game up and as soon as I plugged the controller in, it closed again.
controller used https://www.gamesir.hk/products/gamesir-x2
Phone is a Galaxy A20 with Android 10 on it.

**Comment by daniele-rapagnani** [comment]
@TheUpgrayedd Thanks for reporting your issue! Sadly the game has no crash reporting at the moment so it's really hard to guess what happened but I'm planing on adding crash reporting in the next release or so.
(btw: nice controller!)
