### ISSUE TITLE
Add some way to load different assets so that mods and TC can be played

### ISSUE THREAD

**Issue by daniele-rapagnani** [daniele-rapagnani/alephone-android#26]
If this is not already possibile it should be as easy as adding some path on `/sdcard` in the asset's search path that is scanned first.

Relates to #25.

**Comment by maxcode5ive** [comment]
It will need to read them from the external sdcard as well. There are some TC/mods that are just to big to store on internal storage.

**Comment by daniele-rapagnani** [comment]
@maxcode5ive Yes you are right! Fortunately it shouldn't be a problem because the sdcard is directly accessible as any other location on the filesystem

**Comment by maxcode5ive** [comment]
Thats great. I always thought that was a separate premission.

**Comment by daniele-rapagnani** [comment]
Yes you need to ask for specific permission to read or write from the SD, but once you have it the SD becomes accessible from the filesystem.
