### ISSUE TITLE
Infinity: 2048x2048 tilesets are included, yet can't be used; delete for now until GLES support is added?

### ISSUE THREAD

**Issue by Shockwave508** [daniele-rapagnani/alephone-android#40]
Hi-res assets can be found as plugins for all three games, yet cannot be used at this time due to a lack of OpenGL/GLES rendering. Perhaps these could be deleted for now until a method can be implemented for loading external plugins?

**Comment by daniele-rapagnani** [comment]
In theory I've excluded Hi-res textures from the APKs [here](https://github.com/daniele-rapagnani/alephone-android/blob/master/app/build.gradle#L13). Are you sure about this?

**Comment by Shockwave508** [comment]
I checked, and the hi-res textures are still present in Infinity.
![Screenshot_2021-05-24-06-28-35-936_com alephone marathoninfinity](https://user-images.githubusercontent.com/32436386/119341402-52ab4780-bc59-11eb-904c-60d096695ab0.jpg)
![Screenshot_2021-05-24-06-28-40-191_com alephone marathoninfinity](https://user-images.githubusercontent.com/32436386/119341412-550da180-bc59-11eb-87b2-dc2a76fc8a07.jpg)

**Comment by daniele-rapagnani** [comment]
You are right, thanks!

**Comment by Shockwave508** [comment]
Issue has been solved for a good long while, but is yet to be closed...
